name: Terraform Plan (PR)

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'main'
  workflow_dispatch:

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  GH_ACTIONS_ROLE_ARN: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
  SERVICE_URL_REGISTRATION_API_SOLANA: ${{ secrets.SERVICE_URL_REGISTRATION_API_SOLANA }}
  SERVICE_API_KEY_REGISTRATION_API_SOLANA: ${{ secrets.SERVICE_API_KEY_REGISTRATION_API_SOLANA }}
  TECH_FLORIPA_CERTIFICATE_VALIDATE_URL: ${{ secrets.TECH_FLORIPA_CERTIFICATE_VALIDATE_URL }}
  API_KEY_VALUE: ${{ secrets.API_KEY_VALUE }}


permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  plan:
    name: Checkout and Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ env.GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: TerraformPlanSession

      - name: Check AWS Credentials
        run: aws sts get-caller-identity

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up TF Vars
        run: |
          echo "aws_account_id = \"$AWS_ACCOUNT_ID\"" >> terraform/terraform.tfvars
          echo "aws_region     = \"$AWS_REGION\"" >> terraform/terraform.tfvars
          echo "github_actions_role_arn = \"$GH_ACTIONS_ROLE_ARN\"" >> terraform/terraform.tfvars
          echo "service_url_registration_api_solana     = \"$SERVICE_URL_REGISTRATION_API_SOLANA\"" >> terraform/terraform.tfvars
          echo "service_api_key_registration_api_solana = \"$SERVICE_API_KEY_REGISTRATION_API_SOLANA\"" >> terraform/terraform.tfvars
          echo "tech_floripa_certificate_validate_url   = \"$TECH_FLORIPA_CERTIFICATE_VALIDATE_URL\"" >> terraform/terraform.tfvars
          echo "api_key_value = \"$API_KEY_VALUE\"" >> terraform/terraform.tfvars

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: cd terraform && terraform init -input=false

      - name: Terraform Plan and Generate Markdown
        run: |
          cd terraform
          terraform plan -input=false -out=tfplan

          # Create markdown file with header and code block
          echo "## :terraform: Terraform Plan Summary" > plan-comment.md
          echo "" >> plan-comment.md
          echo '```hcl' >> plan-comment.md
          terraform show -no-color tfplan | sed -n '/Terraform will perform the following actions:/,$p' >> plan-comment.md
          echo '```' >> plan-comment.md

      - name: Comment PR with Terraform Plan
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: terraform/plan-comment.md

      - name: Upload tfplan to S3
        run: aws s3 cp terraform/tfplan s3://tech-floripa-plan-artifacts/${{ github.event.pull_request.number }}/tfplan
